language: python
python:
  - "3.8"
sudo: false

branches:
  only:
    - master

install:
  - pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

cache:
  pip: true

# Use Taipai time
before_script:
  - export TZ=Asia/Taipei

# command to run tests
script:
  #- openssl enc -d -aes-256-cbc -in lope-drive-token.json.enc -out lope-drive-token.json -k $lopedrivetoken
  - unzip -P $drivetoken lope-drive-token.json.zip
  - python3 main.py

before_deploy:
  - rm lope-drive-token.json

deploy:
  provider: pages
  #target-branch: deploy
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  local-dir: docs  # dir to deploy after build
  on:
    branch: master
