
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Documentation

on: 
  push:
  repository_dispatch:

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Build data
      run: |
        sudo timedatectl set-timezone Asia/Taipei
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
        unzip -P ${{ secrets.GDRIVE }} lope-drive-token.json.zip
        python3 main.py
        rm lope-drive-token.json
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        enable_jekyll: false
